FROM microsoft/dotnet

# Args
ARG repositoryUrl=https://github.com/ThiagoBarradas/try.dotnet.core.on.docker
ARG configuration=Release
ARG apiPort=5000
ARG projectName=Testeer

# Change to temp workspace
WORKDIR /temp

# Get code from repository
RUN git clone $repositoryUrl .

# Restore packages and publish app
RUN dotnet restore
RUN dotnet publish -c $configuration

# Copy files to /app
RUN mv /temp/$projectName/bin/$configuration /app
 
# Expose port for the Web API traffic
ENV ASPNETCORE_URLS http://+:$apiPort
EXPOSE $apiPort
 
# Clear temp files
RUN rm -rf /temp 

# Run application
ENTRYPOINT ["dotnet", "run"]

