# Use the standard Microsoft .NET Core container
FROM microsoft/dotnet
 
# Copy our code from the "/src/MyWebApi" folder to the "/app" folder in our container
CMD ls -l
WORKDIR /temp
COPY . .
 
# Expose port 80 for the Web API traffic
ENV ASPNETCORE_URLS http://+:5000
EXPOSE 500
 
# Restore the necessary packages
RUN dotnet restore

COPY ./Testeer/bin/Debug/netcoreapp1.1 /app
WORKDIR /app
RUN rm -rf /temp 

# Build and run the dotnet application from within the container
ENTRYPOINT ["dotnet", "run"]

